### ISSUE TITLE
Ketrew explorable workflow graph in the web UI

### ISSUE THREAD

**Issue by ihodes** [hammerlab/ketrew#258] opened 2015-11-10 21:11 UTC
This would make it far easier to figure out what went wrong & which nodes need fixing.

I'd imagine nodes would be green is succeeded, grey if inactive, blue is running, red if failed. Clicking on them would expand them with basic info within, and clicking again would open the normal target page for them.

**Comment by smondet** [comment] 2015-11-10 21:34
Duplicate of https://github.com/hammerlab/ketrew/issues/207

**Closed by smondet** 2015-11-10 21:34 UTC
Labels: UI
