### ISSUE TITLE
Error showing things still building, but nothing running

### ISSUE THREAD

**Issue by ihodes** [hammerlab/ketrew#509] opened 2017-01-14 18:32 UTC
looking at the status, I get 

> non-fatal error "Client.IO: Unix.Unix_error(Unix.ECONNREFUSED, \"connect\", \"\")" (check-running)

**Comment by smondet** [comment] 2017-01-14 20:13
It looks like a setup problem; like Ketrew cannot talk to Coclobas?

**Comment by ihodes** [comment] 2017-01-14 20:55
I don't think it's setup; it worked for a few days, then stopped working.
Restarting the docker image/relaunching Ketrew et al got it working it.

**Comment by smondet** [comment] 2017-01-15 01:04
Did you just restart or the Sqlite DBs got deleted?

it can also be the coclobas container running out disk space or alike.

**Comment by ihodes** [comment] 2017-01-15 04:04
Just a restart; I don't think I'm running out of disk space (unless Docker has a smaller pool?)

**Comment by smondet** [comment] 2017-01-17 20:29
This could be a coclobas bug (but not Ketrew's; it just could not talk to coclobas and reported all the info it had, thanks Unix…); closing for now unless we have more data on how this can be reproduced.

**Closed by smondet** 2017-01-17 20:29 UTC
Labels: bug

**Comment by ihodes** [comment] 2017-01-17 20:42
What info would be helpful to gather next time this occurs?

**Comment by smondet** [comment] 2017-01-17 20:44
@ihodes 

- the Coclobas logs, 
- the status of the container
- whether `http://<coclobas-host:port>/status` returns something (with `curl` for example)
