### ISSUE TITLE
Error on Target Explorer in ketrew interact

### ISSUE THREAD

**Issue by arahuja** [hammerlab/ketrew#340] opened 2016-02-06 19:14 UTC
```
[ketrew: ERROR]
    Error: Client: HTTP Call (Getting targets → Wrong Json: [ "V0", [
    "Deferred_list_of_target_ids",
    "ketrew_2016-02-06-20h13m27s284ms-UTC_374463206", 11580 ] ])
```

Both the server and client are on
```
ketrew --version
2.0.0+master
``

**Comment by smondet** [comment] 2016-02-06 20:12
I think this is a duplicate of https://github.com/hammerlab/ketrew/issues/224

Sorry I haven't fixed that yet!

**Closed** 2016-02-18 21:40 UTC
Labels: duplicate
